server:
    port: 8886
spring:
    datasource:
        url: jdbc:mysql://xxxxxxxx:3306/xxxxx?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: xxxxxxx
        driver-class-name: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        initialSize: 5
        minIdle: 5
    redis:
        database: 0
        host: xxxxxxxx
        port: 6379
        password: xxxxxx
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
mybatis:
    typeAliasesPackage: com.zhxy.code.entity
    mapper-locations: classpath:mapper/*.xml
    mappers:  com.zhxy.code.base.IBaseMapper
    not-empty: false
    identity: MYSQL
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
#------beetl设置----------
beetl:
    pagePath: /templates                #模板文件位置
    properties: classpath:/beetl.properties     #beetl属性文件


